Fatal error: exception Failure("Expecting 2 arguments in my_func(5, 4, 7)")
make: *** [fail-tooManyArgs.test] Error 2
